version: '3.4'

services:
  situation-room-api:
    image: situation-room-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
